repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: debug-statements
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: check-executables-have-shebangs
    - id: check-ast
    - id: check-byte-order-marker
    - id: check-json
    - id: check-symlinks
    - id: check-vcs-permalinks
    - id: check-xml
    - id: check-yaml
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key
    - id: forbid-new-submodules

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      args: ['--exclude=docs/*,*migrations*', '--ignore=E501,W503,E203']

- repo: https://github.com/timothycrosley/isort
  rev: 5.9.3
  hooks:
    - id: isort

- repo: https://github.com/grantjenks/blue
  rev: v0.7.0
  hooks:
    - id: blue
      args: ['--check', '--diff']

- repo: local
  hooks:
  - id: check-datetime-now
    name: check_datetime_now
    description: Prefer datetime.utcnow()
    language: pygrep
    entry: 'datetime\.now\(\)'
    types: [python]
