version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.0
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: "Restoring dependencies cache"
          keys:
          - v1-dependencies-{{ checksum "poetry.lock" }}

      - run:
          name: "Install dependencies"
          command: |
            poetry self update
            poetry install

      - save_cache:
          name: "Saving dependencies cache"
          key: v1-dependencies-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs

      - restore_cache:
          name: "Restoring hooks cache"
          key: v1-hooks-{{ checksum ".pre-commit-config.yaml" }}

      - run:
          name: "Running linters"
          command: SKIP=no-commit-to-branch poetry run pre-commit run -a -v

      - save_cache:
          name: "Saving hooks cache"
          key: v1-hooks-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - "~/.cache/pre-commit/"

      - run:
          name: "Running tests"
          command: |
            poetry run pytest -vv -s --cov pactum --cov-report=html
            poetry run coveralls

      - store_artifacts:
          path: htmlcov
          destination: test-reports
