version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.10.0
    working_directory: ~/repo
    steps:
      - checkout
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "poetry.lock" }}
#          # fallback to using the latest cache if no exact match is found
#          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . ./venv/bin/activate
            pip install -U poetry coveralls pip setuptools
            poetry install -n --no-ansi
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "poetry.lock" }}
      - run:
          name: run tests
          command: |
            pytest
            coveralls
      - store_artifacts:
          path: test-reports
          destination: test-reports
